# Copyright (c) 2023 Open Risk (https://www.openriskmanagement.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import pandas as pd

column_names = ["POOL_ID",
                "LOAN_ID",
                "ACT_PERIOD",
                "CHANNEL",
                "SELLER",
                "SERVICER",
                "MASTER_SERVICER",
                "ORIG_RATE",
                "CURR_RATE",
                "ORIG_UPB",
                "ISSUANCE_UPB",
                "CURRENT_UPB",
                "ORIG_TERM",
                "ORIG_DATE",
                "FIRST_PAY",
                "LOAN_AGE",
                "REM_MONTHS",
                "ADJ_REM_MONTHS",
                "MATURITY_DATE",
                "OLTV",
                "OCLTV",
                "NUM_BO",
                "DTI",
                "CSCORE_B",
                "CSCORE_C",
                "FIRST_FLAG",
                "PURPOSE",
                "PROP",
                "NO_UNITS",
                "OCC_STAT",
                "STATE",
                "MSA",
                "ZIP",
                "MI_PCT",
                "PRODUCT",
                "PPMT_FLAG",
                "IO",
                "FIRST_PAY_IO",
                "MNTHS_TO_AMTZ_IO",
                "DLQ_STATUS",
                "PMT_HISTORY",
                "MOD_FLAG",
                "MI_CANCEL_FLAG",
                "ZERO_BAL_CODE",
                "ZB_DATE",
                "LAST_UPB",
                "REPURCHASE_DATE",
                "CURR_SCHD_PRNCPL",
                "TOT_SCHD_PRNCPL",
                "UNSCHD_PRNCPL_CURR",
                "LAST_PAID_INSTALLMENT_DATE",
                "FORECLOSURE_DATE",
                "DISPOSITION_DATE",
                "FORECLOSURE_COSTS",
                "PROPERTY_PRESERVATION_AND_REPAIR_COSTS",
                "ASSET_RECOVERY_COSTS",
                "MISCELLANEOUS_HOLDING_EXPENSES_AND_CREDITS",
                "ASSOCIATED_TAXES_FOR_HOLDING_PROPERTY",
                "NET_SALES_PROCEEDS",
                "CREDIT_ENHANCEMENT_PROCEEDS",
                "REPURCHASES_MAKE_WHOLE_PROCEEDS",
                "OTHER_FORECLOSURE_PROCEEDS",
                "NON_INTEREST_BEARING_UPB",
                "PRINCIPAL_FORGIVENESS_AMOUNT",
                "ORIGINAL_LIST_START_DATE",
                "ORIGINAL_LIST_PRICE",
                "CURRENT_LIST_START_DATE",
                "CURRENT_LIST_PRICE",
                "ISSUE_SCOREB",
                "ISSUE_SCOREC",
                "CURR_SCOREB",
                "CURR_SCOREC",
                "MI_TYPE",
                "SERV_IND",
                "CURRENT_PERIOD_MODIFICATION_LOSS_AMOUNT",
                "CUMULATIVE_MODIFICATION_LOSS_AMOUNT", "CURRENT_PERIOD_CREDIT_EVENT_NET_GAIN_OR_LOSS",
                "CUMULATIVE_CREDIT_EVENT_NET_GAIN_OR_LOSS",
                "HOMEREADY_PROGRAM_INDICATOR",
                "FORECLOSURE_PRINCIPAL_WRITE_OFF_AMOUNT",
                "RELOCATION_MORTGAGE_INDICATOR",
                "ZERO_BALANCE_CODE_CHANGE_DATE",
                "LOAN_HOLDBACK_INDICATOR",
                "LOAN_HOLDBACK_EFFECTIVE_DATE",
                "DELINQUENT_ACCRUED_INTEREST",
                "PROPERTY_INSPECTION_WAIVER_INDICATOR",
                "HIGH_BALANCE_LOAN_INDICATOR",
                "ARM_5_YR_INDICATOR",
                "ARM_PRODUCT_TYPE",
                "MONTHS_UNTIL_FIRST_PAYMENT_RESET",
                "MONTHS_BETWEEN_SUBSEQUENT_PAYMENT_RESET",
                "INTEREST_RATE_CHANGE_DATE",
                "PAYMENT_CHANGE_DATE",
                "ARM_INDEX",
                "ARM_CAP_STRUCTURE",
                "INITIAL_INTEREST_RATE_CAP",
                "PERIODIC_INTEREST_RATE_CAP",
                "LIFETIME_INTEREST_RATE_CAP",
                "MARGIN",
                "BALLOON_INDICATOR",
                "PLAN_NUMBER",
                "FORBEARANCE_INDICATOR",
                "HIGH_LOAN_TO_VALUE_HLTV_REFINANCE_OPTION_INDICATOR",
                "DEAL_NAME",
                "RE_PROCS_FLAG",
                "ADR_TYPE",
                "ADR_COUNT",
                "ADR_UPB"]

column_datatypes = {
    "POOL_ID": str,
    "LOAN_ID": str,
    "ACT_PERIOD": str,
    "CHANNEL": str,
    "SELLER": str,
    "SERVICER": str,
    "MASTER_SERVICER": str,
    "ORIG_RATE": float,
    "CURRENT_RATE": float,
    "ORIG_UPB": float,
    "ISSUANCE_UPB": float,
    "CURRENT_UPB": float,
    "ORIG_TERM": pd.Int64Dtype(),
    "ORIG_DATE": str,
    "FIRST_PAY": str,
    "LOAN_AGE": pd.Int64Dtype(),
    "REM_MONTHS": pd.Int64Dtype(),
    "ADJ_REM_MONTHS": pd.Int64Dtype(),
    "MATURITY_DATE": str,
    "OLTV": float,
    "OCLTV": float,
    "NUM_BO": pd.Int64Dtype(),
    "DTI": float,
    "CSCORE_B": float,
    "CSCORE_C": float,
    "FIRST_FLAG": str,
    "PURPOSE": str,
    "PROP": str,
    "NO_UNITS": pd.Int64Dtype(),
    "OCC_STAT": str,
    "STATE": str,
    "MSA": str,
    "ZIP": str,
    "MI_PCT": float,
    "PRODUCT": str,
    "PPMT_FLAG": str,
    "IO": str,
    "FIRST_PAY_IO": pd.Int64Dtype(),
    "MNTHS_TO_AMTZ_IO": pd.Int64Dtype(),
    "DLQ_STATUS": str,
    "PMT_HISTORY": str,
    "MOD_FLAG": str,
    "MI_CANCEL_FLAG": str,
    "ZERO_BAL_CODE": str,
    "ZB_DATE": str,
    "LAST_UPB": float,
    "REPURCHASE_DATE": str,
    "CURR_SCHD_PRNCPL": float,
    "TOT_SCHD_PRNCPL": float,
    "UNSCHD_PRNCPL_CURR": float,
    "LAST_PAID_INSTALLMENT_DATE": str,
    "FORECLOSURE_DATE": str,
    "DISPOSITION_DATE": str,
    "FORECLOSURE_COSTS": float,
    "PROPERTY_PRESERVATION_AND_REPAIR_COSTS": float,
    "ASSET_RECOVERY_COSTS": float,
    "MISCELLANEOUS_HOLDING_EXPENSES_AND_CREDITS": float,
    "ASSOCIATED_TAXES_FOR_HOLDING_PROPERTY": float,
    "NET_SALES_PROCEEDS": float,
    "CREDIT_ENHANCEMENT_PROCEEDS": float,
    "REPURCHASES_MAKE_WHOLE_PROCEEDS": float,
    "OTHER_FORECLOSURE_PROCEEDS": float,
    "NON_INTEREST_BEARING_UPB": float,
    "PRINCIPAL_FORGIVENESS_AMOUNT": float,
    "ORIGINAL_LIST_START_DATE": pd.Int64Dtype(),
    "ORIGINAL_LIST_PRICE": float,
    "CURRENT_LIST_START_DATE": pd.Int64Dtype(),
    "CURRENT_LIST_PRICE": float,
    "ISSUE_SCOREB": float,
    "ISSUE_SCOREC": float,
    "CURR_SCOREB": float,
    "CURR_SCOREC": float,
    "MI_TYPE": str,
    "SERV_IND": str,
    "CURRENT_PERIOD_MODIFICATION_LOSS_AMOUNT": float,
    "CUMULATIVE_MODIFICATION_LOSS_AMOUNT": float,
    "CURRENT_PERIOD_CREDIT_EVENT_NET_GAIN_OR_LOSS": float,
    "CUMULATIVE_CREDIT_EVENT_NET_GAIN_OR_LOSS": float,
    "HOMEREADY_PROGRAM_INDICATOR": str,
    "FORECLOSURE_PRINCIPAL_WRITE_OFF_AMOUNT": float,
    "RELOCATION_MORTGAGE_INDICATOR": str,
    "ZERO_BALANCE_CODE_CHANGE_DATE": pd.Int64Dtype(),
    "LOAN_HOLDBACK_INDICATOR": str,
    "LOAN_HOLDBACK_EFFECTIVE_DATE": pd.Int64Dtype(),
    "DELINQUENT_ACCRUED_INTEREST": float,
    "PROPERTY_INSPECTION_WAIVER_INDICATOR": str,
    "HIGH_BALANCE_LOAN_INDICATOR": str,
    "ARM_5_YR_INDICATOR": str,
    "ARM_PRODUCT_TYPE": str,
    "MONTHS_UNTIL_FIRST_PAYMENT_RESET": pd.Int64Dtype(),
    "MONTHS_BETWEEN_SUBSEQUENT_PAYMENT_RESET": pd.Int64Dtype(),
    "INTEREST_RATE_CHANGE_DATE": pd.Int64Dtype(),
    "PAYMENT_CHANGE_DATE": pd.Int64Dtype(),
    "ARM_INDEX": str,
    "ARM_CAP_STRUCTURE": str,
    "INITIAL_INTEREST_RATE_CAP": float,
    "PERIODIC_INTEREST_RATE_CAP": float,
    "LIFETIME_INTEREST_RATE_CAP": float,
    "MARGIN": float,
    "BALLOON_INDICATOR": str,
    "PLAN_NUMBER": str,
    "FORBEARANCE_INDICATOR": str,
    "HIGH_LOAN_TO_VALUE_HLTV_REFINANCE_OPTION_INDICATOR": str,
    "DEAL_NAME": str,
    "RE_PROCS_FLAG": str,
    "ADR_TYPE": str,
    "ADR_COUNT": pd.Int64Dtype(),
    "ADR_UPB": float,
}

column_names_dict = {
    'POOL_ID': 1,
    'LOAN_ID': 2,
    'ACT_PERIOD': 3,
    'CHANNEL': 4,
    'SELLER': 5,
    'SERVICER': 6,
    'MASTER_SERVICER': 7,
    'ORIG_RATE': 8,
    'CURR_RATE': 9,
    'ORIG_UPB': 10,
    'ISSUANCE_UPB': 11,
    'CURRENT_UPB': 12,
    'ORIG_TERM': 13,
    'ORIG_DATE': 14,
    'FIRST_PAY': 15,
    'LOAN_AGE': 16,
    'REM_MONTHS': 17,
    'ADJ_REM_MONTHS': 18,
    'MATURITY_DATE': 19,
    'OLTV': 20,
    'OCLTV': 21,
    'NUM_BO': 22,
    'DTI': 23,
    'CSCORE_B': 24,
    'CSCORE_C': 25,
    'FIRST_FLAG': 26,
    'PURPOSE': 27,
    'PROP': 28,
    'NO_UNITS': 29,
    'OCC_STAT': 30,
    'STATE': 31,
    'MSA': 32,
    'ZIP': 33,
    'MI_PCT': 34,
    'PRODUCT': 35,
    'PPMT_FLAG': 36,
    'IO': 37,
    'FIRST_PAY_IO': 38,
    'MNTHS_TO_AMTZ_IO': 39,
    'DLQ_STATUS': 40,
    'PMT_HISTORY': 41,
    'MOD_FLAG': 42,
    'MI_CANCEL_FLAG': 43,
    'ZERO_BAL_CODE': 44,
    'ZB_DATE': 45,
    'LAST_UPB': 46,
    'RPRCH_DATE': 47,
    'CURR_SCHD_PRNCPL': 48,
    'TOT_SCHD_PRNCPL': 49,
    'UNSCHD_PRNCPL_CURR': 50,
    'LAST_PAID_INSTALLMENT_DATE': 51,
    'FORECLOSURE_DATE': 52,
    'DISPOSITION_DATE': 53,
    'FORECLOSURE_COSTS': 54,
    'PROPERTY_PRESERVATION_AND_REPAIR_COSTS': 55,
    'ASSET_RECOVERY_COSTS': 56,
    'MISCELLANEOUS_HOLDING_EXPENSES_AND_CREDITS': 57,
    'ASSOCIATED_TAXES_FOR_HOLDING_PROPERTY': 58,
    'NET_SALES_PROCEEDS': 59,
    'CREDIT_ENHANCEMENT_PROCEEDS': 60,
    'REPURCHASES_MAKE_WHOLE_PROCEEDS': 61,
    'OTHER_FORECLOSURE_PROCEEDS': 62,
    'NON_INTEREST_BEARING_UPB': 63,
    'PRINCIPAL_FORGIVENESS_AMOUNT': 64,
    'ORIGINAL_LIST_START_DATE': 65,
    'ORIGINAL_LIST_PRICE': 66,
    'CURRENT_LIST_START_DATE': 67,
    'CURRENT_LIST_PRICE': 68,
    'ISSUE_SCOREB': 69,
    'ISSUE_SCOREC': 70,
    'CURR_SCOREB': 71,
    'CURR_SCOREC': 72,
    'MI_TYPE': 73,
    'SERV_IND': 74,
    'CURRENT_PERIOD_MODIFICATION_LOSS_AMOUNT': 75,
    'CUMULATIVE_MODIFICATION_LOSS_AMOUNT': 76,
    'CURRENT_PERIOD_CREDIT_EVENT_NET_GAIN_OR_LOSS': 77,
    'CUMULATIVE_CREDIT_EVENT_NET_GAIN_OR_LOSS': 78,
    'HOMEREADY_PROGRAM_INDICATOR': 79,
    'FORECLOSURE_PRINCIPAL_WRITE_OFF_AMOUNT': 80,
    'RELOCATION_MORTGAGE_INDICATOR': 81,
    'ZERO_BALANCE_CODE_CHANGE_DATE': 82,
    'LOAN_HOLDBACK_INDICATOR': 83,
    'LOAN_HOLDBACK_EFFECTIVE_DATE': 84,
    'DELINQUENT_ACCRUED_INTEREST': 85,
    'PROPERTY_INSPECTION_WAIVER_INDICATOR': 86,
    'HIGH_BALANCE_LOAN_INDICATOR': 87,
    'ARM_5_YR_INDICATOR': 88,
    'ARM_PRODUCT_TYPE': 89,
    'MONTHS_UNTIL_FIRST_PAYMENT_RESET': 90,
    'MONTHS_BETWEEN_SUBSEQUENT_PAYMENT_RESET': 91,
    'INTEREST_RATE_CHANGE_DATE': 92,
    'PAYMENT_CHANGE_DATE': 93,
    'ARM_INDEX': 94,
    'ARM_CAP_STRUCTURE': 95,
    'INITIAL_INTEREST_RATE_CAP': 96,
    'PERIODIC_INTEREST_RATE_CAP': 97,
    'LIFETIME_INTEREST_RATE_CAP': 98,
    'MARGIN': 99,
    'BALLOON_INDICATOR': 100,
    'PLAN_NUMBER': 101,
    'FORBEARANCE_INDICATOR': 102,
    'HIGH_LOAN_TO_VALUE_HLTV_REFINANCE_OPTION_INDICATOR': 103,
    'DEAL_NAME': 104,
    'RE_PROCS_FLAG': 105,
    'ADR_TYPE': 106,
    'ADR_COUNT': 107,
    'ADR_UPB': 108}

static_fields = ['LOAN_ID', 'CHANNEL', 'SELLER', 'ORIG_RATE', 'ORIG_UPB', 'ORIG_TERM', 'ORIG_DATE',
                 'FIRST_PAY', 'OLTV', 'OCLTV', 'NUM_BO', 'DTI', 'CSCORE_B', 'CSCORE_C', 'FIRST_FLAG', 'PURPOSE', 'PROP',
                 'NO_UNITS', 'OCC_STAT', 'MSA', 'STATE', 'ZIP', 'MI_PCT', 'PRODUCT', 'MI_TYPE',
                 'RELOCATION_MORTGAGE_INDICATOR', 'HIGH_BALANCE_LOAN_INDICATOR', 'PPMT_FLAG', 'IO']

counterparty_static = ['LOAN_ID', 'NUM_BO', 'DTI', 'CSCORE_B', 'CSCORE_C', 'FIRST_FLAG']

counterparty_dynamic = ['LOAN_ID', 'ACT_PERIOD', 'CURR_SCOREB', 'CURR_SCOREC']

loan_static = ['LOAN_ID',
               'SELLER',
               'ACT_PERIOD',
               'CHANNEL',
               'ORIG_RATE',
               'ORIG_UPB',
               'ORIG_TERM',
               'ORIG_DATE',
               'FIRST_PAY',
               'OLTV',
               'PURPOSE',
               'PRODUCT',
               'RELOCATION_MORTGAGE_INDICATOR',
               'HIGH_BALANCE_LOAN_INDICATOR',
               'MI_PCT',
               'MI_TYPE',
               'OCLTV',
               'PPMT_FLAG',
               'IO']

loan_dynamic = ['LOAN_ID',
                'ACT_PERIOD',
                'HIGH_LOAN_TO_VALUE_HLTV_REFINANCE_OPTION_INDICATOR',
                'ZERO_BAL_CODE',
                'ZB_DATE',
                'LAST_UPB',
                'TOT_SCHD_PRNCPL',
                'LAST_PAID_INSTALLMENT_DATE',
                'MNTHS_TO_AMTZ_IO',
                'MI_CANCEL_FLAG',
                'CURR_SCHD_PRNCPL',
                'UNSCHD_PRNCPL_CURR',
                'ZERO_BALANCE_CODE_CHANGE_DATE',
                'LOAN_HOLDBACK_INDICATOR',
                'LOAN_HOLDBACK_EFFECTIVE_DATE',
                'INTEREST_RATE_CHANGE_DATE',
                'PAYMENT_CHANGE_DATE',
                'SERVICER',
                'CURR_RATE',
                'CURRENT_UPB',
                'LOAN_AGE',
                'REM_MONTHS',
                'ADJ_REM_MONTHS',
                'MATURITY_DATE',
                'SERV_IND']

property_collateral_static = ['LOAN_ID', 'PROP', 'NO_UNITS', 'OCC_STAT', 'STATE', 'MSA', 'ZIP']

property_collateral_dynamic = ['LOAN_ID', 'ACT_PERIOD', 'PROPERTY_PRESERVATION_AND_REPAIR_COSTS',
                               'MISCELLANEOUS_HOLDING_EXPENSES_AND_CREDITS',
                               'ASSOCIATED_TAXES_FOR_HOLDING_PROPERTY',
                               'PROPERTY_INSPECTION_WAIVER_INDICATOR']

if __name__ == '__main__':

    print(len(static_fields))
