[project]
name = "academy-course-pyt37067"
version = "0.1.0"
description = "Resources for Open Risk Academy Course: Processing US Agency Mortgage Data with Awk and Pandas - Part 2: Performing Book"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
]
